// Material-Ui used in this task

import Head from "next/head";
// Material/Ui Components
import CssBaseline from "@mui/material/CssBaseline";
import Divider from "@mui/material/Divider";
// Components
import Breadcrumbs from "../components/Breadcrumbs";
import Table from "../components/Table/Table";
export default function Home({ apiData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CssBaseline />
        <div style={{ marginLeft: "25px", marginTop: "30px", width: "100%" }}>
          <Breadcrumbs />
          <Divider
            variant="middle"
            sx={{ width: "100%", marginLeft: "10px", marginBottom: "10px" }}
          />
          <Table appData={apiData} />
        </div>
      </main>
    </div>
  );
}

// Getting the Api Data used getStaticProps because it's executed on the server
export const getStaticProps = async () => {
  const res = await fetch(
    "https://run.mocky.io/v3/a2fbc23e-069e-4ba5-954c-cd910986f40f"
  );
  const data = await res.json();
  console.log("data", data);
  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { apiData: data },
  };
};
